In [2]:
import numpy as np
import pandas as pd

1. Create a nested list which contains the name,age and race of 10 people each. Turn this list to a dataframe.

In [3]:
#Turning a list into a dataframe
data = [["Rita",25,"SouthAmerican"],["Andrew",30,"NorthAmerican"],["Yomi",45,"African"],["Emmy",30,"Austrialian"],\
        ["Nandy",18,"Asian"],["Karan",20,"Asian"],["Faith",25,"NorthAmerican"],["Joe",30,"NorthAmerican"],["Josy",27,"Asian"],\
        ["Deja",28,"African"]]
df = pd.DataFrame(data)
print(df)

        0   1              2
0    Rita  25  SouthAmerican
1  Andrew  30  NorthAmerican
2    Yomi  45        African
3    Emmy  30    Austrialian
4   Nandy  18          Asian
5   Karan  20          Asian
6   Faith  25  NorthAmerican
7     Joe  30  NorthAmerican
8    Josy  27          Asian
9    Deja  28        African


2. Label the columns with the appropriate column names.

In [4]:
#To add headers to the columns.
df.columns = ["Name","Age","Race"]
df

Name  Age           Race
0    Rita   25  SouthAmerican
1  Andrew   30  NorthAmerican
2    Yomi   45        African
3    Emmy   30    Austrialian
4   Nandy   18          Asian
5   Karan   20          Asian
6   Faith   25  NorthAmerican
7     Joe   30  NorthAmerican
8    Josy   27          Asian
9    Deja   28        African

3. Add a new column to your dataframe called weight and enter values for it.

In [5]:
#To add another coulmn to the dataframe
df["Weight(kg)"]=[65, 80, 100, 75, 80, 55,78,80,100,90]
df


Name  Age           Race  Weight(kg)
0    Rita   25  SouthAmerican          65
1  Andrew   30  NorthAmerican          80
2    Yomi   45        African         100
3    Emmy   30    Austrialian          75
4   Nandy   18          Asian          80
5   Karan   20          Asian          55
6   Faith   25  NorthAmerican          78
7     Joe   30  NorthAmerican          80
8    Josy   27          Asian         100
9    Deja   28        African          90

4. Change the name of the column from "weight" to "height"

In [6]:
df = df.rename(columns= {"Weight(kg)":"Height"})
df

Name  Age           Race  Height
0    Rita   25  SouthAmerican      65
1  Andrew   30  NorthAmerican      80
2    Yomi   45        African     100
3    Emmy   30    Austrialian      75
4   Nandy   18          Asian      80
5   Karan   20          Asian      55
6   Faith   25  NorthAmerican      78
7     Joe   30  NorthAmerican      80
8    Josy   27          Asian     100
9    Deja   28        African      90

5. Change the row index to another indexing of your choice

In [7]:
#To change the row inedx

df.index =["A","B","C","D","E","F","G","H","I","J"]
df

Name  Age           Race  Height
A    Rita   25  SouthAmerican      65
B  Andrew   30  NorthAmerican      80
C    Yomi   45        African     100
D    Emmy   30    Austrialian      75
E   Nandy   18          Asian      80
F   Karan   20          Asian      55
G   Faith   25  NorthAmerican      78
H     Joe   30  NorthAmerican      80
I    Josy   27          Asian     100
J    Deja   28        African      90

6. Select/display only the age and race columns.

In [8]:
#To display one or more columns.

df.loc["A":"J","Age":"Race"]


Age           Race
A   25  SouthAmerican
B   30  NorthAmerican
C   45        African
D   30    Austrialian
E   18          Asian
F   20          Asian
G   25  NorthAmerican
H   30  NorthAmerican
I   27          Asian
J   28        African

7. Select / display the first five names and their age

In [16]:
#to display the first five names and their age
df.loc["A":"E",["Name","Age"]]


Name  Age
A    Rita   25
B  Andrew   30
C    Yomi   45
D    Emmy   30
E   Nandy   18

8. Select all rows but only the third column.

In [12]:
#selecting all rows but only the third column
df.loc["A":"J","Race"]


A    SouthAmerican
B    NorthAmerican
C          African
D      Austrialian
E            Asian
F            Asian
G    NorthAmerican
H    NorthAmerican
I            Asian
J          African
Name: Race, dtype: object

9. Write some code to return the row index back to the default numbering before it was changed

In [19]:
df.reset_index(inplace=True,drop=True)
df

Name  Age           Race  Height
0    Rita   25  SouthAmerican      65
1  Andrew   30  NorthAmerican      80
2    Yomi   45        African     100
3    Emmy   30    Austrialian      75
4   Nandy   18          Asian      80
5   Karan   20          Asian      55
6   Faith   25  NorthAmerican      78
7     Joe   30  NorthAmerican      80
8    Josy   27          Asian     100
9    Deja   28        African      90

10. Create a dataframe from the dictionary below.Using the dataframe select books with ratings not less than 200000


In [22]:
#Create a dataframe from the dictionary below
chimamda={"Books":["Americanah","Half of a Yellow Sun","Purple Hibicus",
                   "The Thing Around Your Neck","We Should All Be Feminists"],
         "Ratings":[297972,120131,5116,32064,204882]}
chimamdaratings=pd.DataFrame(chimamda)
print(chimamdaratings)

                        Books  Ratings
0                  Americanah   297972
1        Half of a Yellow Sun   120131
2              Purple Hibicus     5116
3  The Thing Around Your Neck    32064
4  We Should All Be Feminists   204882


In [33]:
#Using the dataframe select books with ratings not less than 200000
chimamdaratings.loc[chimamdaratings["Ratings"]>200000, "Books"]

0                    Americanah
4    We Should All Be Feminists
Name: Books, dtype: object

11. Create a numpy array with data type boolean.

In [45]:
booleanarray = np.array([10, 100.72, 0, "Faith", 'a',0.9,""," ",True,False], dtype=bool)
print(booleanarray)


[ True  True False  True  True  True False  True  True False]


12. Convert the following array to an integer.

In [46]:
#To change an array to an integer

a=np.array([[True,False,False],
           [True,True,True],
           [False,False,False]], dtype=int)
print(a)

[[1 0 0]
 [1 1 1]
 [0 0 0]]


13.Stack these numpy arrays - vertically and horizontally

In [92]:
a=np.array([[7,8,9],
           [10,11,12]])

aa=np.array([[1,2,3],
            [4,5,6]])

#aaah= np.hstack((a,aa))
aaah1= np.vstack((a,aa))

aaah
aaah1


array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

14.Create 2 3D arrays add them together to create a new array, then sort the new array.

In [107]:
#Creating 2 3D arrays
arr1 = np.array([[[1,9,8],[5,6,10],[7,3,2],[8,11,10]]])

arr2 = np.array([[[13,1,15],[16,1,18],[1,2,25],[22,23,0]]])

#adding the array
a=((arr1 + arr2))

print (a)

[[[14 10 23]
  [21  7 28]
  [ 8  5 27]
  [30 34 10]]]


In [112]:
#sorting the array by row
a.sort(axis=1)
print(a)

[[[ 8  5 10]
  [14  7 23]
  [21 10 27]
  [30 34 28]]]


15.Using step slicing , slice the array below from any position using 3 steps.

In [124]:
a=np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])

#Step1:Slicing from index 1 to the index 9:
print(a[1:9])

#Step 2:Slicing from index 2 to the end of the array:
print(a[2:])

#Step 3:Slicing from index 2 to the begin of the array:
print(a[:2])

[8 7 1 0 9 4 2 6]
[7 1 0 9 4 2 6 3]
[5 8]
